/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.UI.team;

import static com.mycompany.UI.frame.Main.conn;
import static com.mycompany.UI.team.TeamManagement.TeamIDmanager;
import com.mycompany.access.PlayerAccess;
import com.mycompany.access.TeamAccess;
import com.mycompany.model.Player;
import com.mycompany.model.PlayerOfTeam;
import com.mycompany.service.UserSession;
import com.toedter.calendar.JDateChooser;
import java.awt.GridLayout;
import java.sql.Connection;
import java.sql.Date;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Minh Dep Trai
 */
public class PlayerTeamList extends javax.swing.JPanel {

    /**
     * Creates new form PlayerTeamList
     */
    private TeamCareMain team;
    public PlayerTeamList(TeamCareMain team) throws SQLException {
        this.team = team;
        initComponents();
        addDataTable();
    }
    public PlayerTeamList() {
        initComponents();
    }
    public void addDataTable() throws SQLException{
        TeamAccess tacc = new TeamAccess(conn);
        List<PlayerOfTeam> data = tacc.listPlayerOfTeam(TeamIDmanager);
        DefaultTableModel model = (DefaultTableModel) playerTable.getModel();
        model.setRowCount(0);
        for(PlayerOfTeam p: data){
            model.addRow(new Object[]{
                p.team(),
                p.name(),
                p.pos(),
                p.shirtNum(),
                p.goal(),
                p.yellowCard(),
                p.redCard(),
                p.contractEnd()
                }
            );
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        playerTable = new javax.swing.JTable();

        jPanel4.setBackground(new java.awt.Color(30, 30, 30));

        playerTable.setBackground(new java.awt.Color(153, 153, 153));
        playerTable.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        playerTable.setForeground(new java.awt.Color(255, 153, 51));
        playerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Team", "Name", "Position", "Shirt Number", "Goal", "Yellow Card", "Red Card", "Contact End"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(playerTable);
        if (playerTable.getColumnModel().getColumnCount() > 0) {
            playerTable.getColumnModel().getColumn(0).setHeaderValue("Team");
            playerTable.getColumnModel().getColumn(4).setHeaderValue("Goal");
            playerTable.getColumnModel().getColumn(5).setHeaderValue("Yellow Card");
            playerTable.getColumnModel().getColumn(6).setHeaderValue("Red Card");
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 826, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 657, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable playerTable;
    // End of variables declaration//GEN-END:variables
}
