/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.UI.team;

import javax.swing.SwingUtilities;
import com.formdev.flatlaf.FlatDarkLaf;
import com.mycompany.UI.frame.HomeFrame;
import static com.mycompany.UI.frame.Main.conn;
import static com.mycompany.UI.team.TeamManagement.TeamIDmanager;
import com.mycompany.access.RankingAccess;
import static com.mycompany.access.RankingAccess.listRankingTableByPoint;
import com.mycompany.access.TeamAccess;
import com.mycompany.access.TournamentAccess;
import com.mycompany.model.Ranking;
import com.mycompany.model.Tournament;
import java.awt.Color;
import java.awt.event.ItemEvent;
import java.sql.SQLException;
import java.util.List;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Minh Dep Trai
 */
public class TeamCareMain extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TeamCareMain.class.getName());

    /**
     * Creates new form TeamManagement1
     */
    public PlayerTeamList list;
    public NextScheduleTeam nextmatch;
    public final void setPlayerTeamList() throws SQLException {
        if(list == null) {
            list = new PlayerTeamList(this);
        }
        jPanel2.removeAll();
        jPanel2.add(list);
        SwingUtilities.updateComponentTreeUI(jPanel2);
    }
    
    public final void setNextScheduleTeam() throws SQLException {
        if(nextmatch == null) {
            nextmatch = new NextScheduleTeam(this);
        }
        jPanel2.removeAll();
        jPanel2.add(nextmatch);
        SwingUtilities.updateComponentTreeUI(jPanel2);
    }
    
    public TeamCareMain() throws SQLException {
        initComponents();
        setPlayerTeamList();
        setNextScheduleTeam();
        TournamentAccess tacc = new TournamentAccess(conn);
        TeamAccess team = new TeamAccess(conn);
        List<Tournament> tours = tacc.listTournamentByTeamId(TeamIDmanager);
        nameL.setText(team.findTeamById(TeamIDmanager).nameTeam());
        
        cbTour.removeAllItems();

        for (Tournament t : tours) {
            cbTour.addItem(t);
        }

        cbTour.addItemListener(e -> {
            if (e.getStateChange() == ItemEvent.SELECTED) {
                Tournament selectedTour = (Tournament) cbTour.getSelectedItem();

                if (selectedTour != null) {
                    try { 
                        addTableData(selectedTour.id());
                    } catch (SQLException ex) {
                        System.getLogger(TeamCareMain.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                    }
                }
            }
        });
        if (cbTour.getItemCount() > 0) {
            cbTour.setSelectedIndex(0);
            Tournament first = (Tournament) cbTour.getItemAt(0);
            addTableData(first.id());
        }
    }
    private void addTableData(int tourId) throws SQLException {
        RankingAccess racc = new RankingAccess(conn);
        List<Ranking> rankings = racc.listRanking(tourId); 
        rankings = listRankingTableByPoint(rankings);
        DefaultTableModel model = (DefaultTableModel) rankingTable.getModel();
        model.setRowCount(0);

        for (Ranking r : rankings) {
            model.addRow(new Object[]{
                r.teamName(),
                r.points(),
                r.played(),
                r.wins(),
                r.draws(),
                r.losses(),
                r.goals(),
                r.against(),
                r.diff()
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        rankingTable = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        cbTour = new javax.swing.JComboBox<>();
        nameL = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setBackground(new java.awt.Color(30, 30, 30));

        jButton2.setBackground(new java.awt.Color(40, 40, 40));
        jButton2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("PlayerList");
        jButton2.setBorder(null);
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton5.setBackground(new java.awt.Color(77, 120, 204));
        jButton5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton5.setText("Matches");
        jButton5.setBorder(null);
        jButton5.addActionListener(this::jButton5ActionPerformed);

        rankingTable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rankingTable.setForeground(new java.awt.Color(102, 153, 255));
        rankingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Point", "Played", "Win", "Draw", "Lose", "Goal", "Conceded", "Dif"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        rankingTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(rankingTable);

        jButton4.setText("Back");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        cbTour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        nameL.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        nameL.setForeground(new java.awt.Color(102, 153, 255));
        nameL.setText("Team Name:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(nameL, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cbTour, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(129, 129, 129)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbTour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameL, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel2.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 773, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jButton2.setBackground(new Color(77,120,204));
        jButton5.setBackground(new Color(40,40,40));
        try {
            setPlayerTeamList();               // TODO add your handling code here:
        } catch (SQLException ex) {
            System.getLogger(TeamCareMain.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jButton5.setBackground(new Color(77,120,204));
        jButton2.setBackground(new Color(40,40,40));
        try {
            setNextScheduleTeam();        // TODO add your handling code here:
        } catch (SQLException ex) {
            System.getLogger(TeamCareMain.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new HomeFrame().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jButton2.setBackground(new Color(40,40,40));
        jButton5.setBackground(new Color(40,40,40)); 
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new FlatDarkLaf());
        } catch (UnsupportedLookAndFeelException ex) {
        }


        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new TeamManagement1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Object> cbTour;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameL;
    private javax.swing.JTable rankingTable;
    // End of variables declaration//GEN-END:variables
}
