/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.UI.transfer;

import com.mycompany.UI.frame.HomeFrame;
import static com.mycompany.UI.frame.Main.conn;
import com.mycompany.access.TeamAccess;
import com.mycompany.access.TransferAccess;
import com.mycompany.model.Transfer;
import com.mycompany.service.UserSession;
import static com.mycompany.service.UserSession.getMyTeamId;
import static com.mycompany.service.UserSession.isAdmin;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Minh Dep Trai
 */
public class TransferManagement extends javax.swing.JPanel {

    /**
     * Creates new form ScheduleManagement
     */
    private HomeFrame frame;
    public TransferManagement(HomeFrame frame) {
        this.frame = frame;
        initComponents();
        addDatatoTable();
        addDatafromTable();
        accept.setVisible(false);
        reject.setVisible(false);
        if(!isAdmin()){
            TeamAccess tacc = new TeamAccess(conn);
            String t = tacc.findTeamById(UserSession.getMyTeamId()).nameTeam();
            name.setText(t);
        } else name.setText("Admin");
    }
    public TransferManagement() {
        initComponents();
    }
    
    public void addDatatoTable(){
        TransferAccess tacc = new TransferAccess(conn);
        List<Transfer> data = new ArrayList<>();
        if(!isAdmin()){
            data = tacc.getPendingTransfers(getMyTeamId());
        } else {
            data = tacc.getAllTransfers();
        }
        DefaultTableModel model = (DefaultTableModel) toTable.getModel();
        model.setRowCount(0);
        for(Transfer t: data){
            model.addRow(new Object[]{
                t.id(),
                t.playerName(),
                t.toTeamName(),
                t.fee(),
                t.salary(),
                t.offerDate(),
                t.state()
                }
            );
        }
    }
    
    public void addDatafromTable(){
        TransferAccess tacc = new TransferAccess(conn);
        List<Transfer> data = new ArrayList<>();
        if(!isAdmin()){
            data = tacc.getSentOffers(getMyTeamId());
        } else {
            data = tacc.getAllTransfers();
        }
        DefaultTableModel model = (DefaultTableModel) fromTable.getModel();
        model.setRowCount(0);
        for(Transfer t: data){
            model.addRow(new Object[]{
                t.id(),
                t.playerName(),
                t.toTeamName(),
                t.fee(),
                t.salary(),
                t.offerDate(),
                t.state()
                }
            );
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        toTable = new javax.swing.JTable();
        accept = new javax.swing.JButton();
        name = new javax.swing.JLabel();
        name1 = new javax.swing.JLabel();
        reject = new javax.swing.JButton();
        refesh = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        fromTable = new javax.swing.JTable();
        add = new javax.swing.JButton();
        name2 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(30, 30, 30));
        jPanel2.setPreferredSize(new java.awt.Dimension(1103, 1498));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(187, 187, 187));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Transfer Management");

        jPanel3.setBackground(new java.awt.Color(30, 30, 30));

        toTable.setBackground(new java.awt.Color(153, 153, 153));
        toTable.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        toTable.setForeground(new java.awt.Color(204, 85, 0));
        toTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "From", "Fee", "Offered Salary", "Date", "State"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        toTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(toTable);

        accept.setBackground(new java.awt.Color(0, 153, 0));
        accept.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        accept.setForeground(new java.awt.Color(255, 255, 255));
        accept.setText("Accept");
        accept.addActionListener(this::acceptActionPerformed);

        name.setFont(new java.awt.Font("Segoe UI Semibold", 1, 48)); // NOI18N
        name.setForeground(new java.awt.Color(102, 153, 255));
        name.setText("Name Team");

        name1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        name1.setForeground(new java.awt.Color(204, 85, 0));
        name1.setText("Offer Received:");

        reject.setBackground(new java.awt.Color(153, 0, 0));
        reject.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        reject.setForeground(new java.awt.Color(255, 255, 255));
        reject.setText("Reject");
        reject.addActionListener(this::rejectActionPerformed);

        refesh.setBackground(new java.awt.Color(102, 102, 102));
        refesh.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        refesh.setForeground(new java.awt.Color(255, 255, 255));
        refesh.setText("Refesh");
        refesh.addActionListener(this::refeshActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1025, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(name1, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(accept)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(reject))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(refesh)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(34, Short.MAX_VALUE)
                        .addComponent(refesh)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(reject)
                        .addComponent(accept)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButton3.setText("Back");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        fromTable.setBackground(new java.awt.Color(153, 153, 153));
        fromTable.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        fromTable.setForeground(new java.awt.Color(204, 85, 0));
        fromTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "To", "Fee", "Offered Salary", "Date", "State"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(fromTable);

        add.setBackground(new java.awt.Color(204, 85, 0));
        add.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("Add");
        add.addActionListener(this::addActionPerformed);

        name2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        name2.setForeground(new java.awt.Color(204, 85, 0));
        name2.setText("Offer Sended:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButton3)
                        .addGap(234, 234, 234)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(name2, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(add))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1025, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add)
                    .addComponent(name2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(587, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1246, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void acceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptActionPerformed
        int selectedRow = toTable.getSelectedRow();

        int transferId = (int) toTable.getValueAt(selectedRow, 0);
        String state =  toTable.getValueAt(selectedRow, 6).toString();
        if(state.equals("pending")){
            accept.setVisible(true);
            reject.setVisible(true);
        }
        String playerName = toTable.getValueAt(selectedRow, 1).toString();
        String yearsStr = JOptionPane.showInputDialog(this, 
                "Sell " + playerName + "!\nEnter new contract lenght:", 
                "3");

        if (yearsStr == null) return; 

        try {
            int years = Integer.parseInt(yearsStr);
            if (years <= 0) throw new NumberFormatException();
            LocalDate newEndDate = LocalDate.now().plusYears(years);
            TransferAccess tacc = new TransferAccess(conn);
            String msg = tacc.respondToTransfer(transferId, true, newEndDate);
            JOptionPane.showMessageDialog(this, msg);
            addDatatoTable(); 

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Enter a valid year-contract ( 1, 2, 3...)");
        }
    }//GEN-LAST:event_acceptActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        frame.setMatchAdd();                // TODO add your handling code here:
    }//GEN-LAST:event_addActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        frame.setHomePanel();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void rejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectActionPerformed
        int selectedRow = toTable.getSelectedRow();
       
        int transferId = (int) toTable.getValueAt(selectedRow, 0);
        int confirm = JOptionPane.showConfirmDialog(this, 
                "Reject this offer?", "Reject", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            TransferAccess tacc = new TransferAccess(conn);
            String msg = tacc.respondToTransfer(transferId, false, null);

            JOptionPane.showMessageDialog(this, msg);
            addDatatoTable();
        }
    }//GEN-LAST:event_rejectActionPerformed

    private void toTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toTableMouseClicked
        int selectedRow = toTable.getSelectedRow();
        String state =  toTable.getValueAt(selectedRow, 6).toString();
        accept.setVisible(state.equals("pending"));
        reject.setVisible(state.equals("pending"));
        
        revalidate();
        repaint();
    }//GEN-LAST:event_toTableMouseClicked

    private void refeshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refeshActionPerformed
        addDatatoTable();
        addDatafromTable();
    }//GEN-LAST:event_refeshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accept;
    private javax.swing.JButton add;
    private javax.swing.JTable fromTable;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel name;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel name2;
    private javax.swing.JButton refesh;
    private javax.swing.JButton reject;
    private javax.swing.JTable toTable;
    // End of variables declaration//GEN-END:variables
}
