/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.UI.match;

import com.mycompany.UI.frame.HomeFrame;
import static com.mycompany.UI.frame.Main.conn;
import com.mycompany.access.MatchAccess;
import com.mycompany.access.TeamAccess;
import com.mycompany.model.Match;
import com.mycompany.model.MatchEventTemp;
import com.mycompany.model.Player;
import com.mycompany.model.Versus;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Minh Dep Trai
 */
public class MatchMoment extends javax.swing.JPanel {

    /**
     * Creates new form MatchMoment
     */
    private HomeFrame frame;
    
    private int currentMatchId;
    private int homeTeamId;
    private int awayTeamId;
    private List<MatchEventTemp> tempEvents = new ArrayList<>();
    public MatchMoment(HomeFrame frame,int matchId, int homeId, int awayId) {
        this.frame = frame;
        initComponents();
        this.homeTeamId = homeId;
        this.awayTeamId = awayId;
        this.currentMatchId = matchId;
        loadPlayers(homeId, homecb);
        loadPlayers(awayId, awaycb);
        MatchAccess macc = new MatchAccess(conn);
        Versus ver = macc.getVersusByMatchId(matchId);
        label.setText(ver.homeName() + " vs " + ver.awayName() + " | " + ver.tourName());
        setupExclusiveCombos();
    }
    public MatchMoment() {
        initComponents();
    }
    private void loadPlayers(int teamId, JComboBox cb) {
        TeamAccess tacc = new TeamAccess(conn);
        List<Player> players = tacc.listPlayByTeam(teamId);
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        
        for(Player p: players){
            model.addElement(p);
        }
        cb.setModel(model);
        cb.setSelectedIndex(-1);
    }
    private void setupExclusiveCombos() {
        homecb.addActionListener(e -> {
            if (homecb.getSelectedIndex() != -1) {
                awaycb.setSelectedIndex(-1); 
            }
        });
        awaycb.addActionListener(e -> {
            if (awaycb.getSelectedIndex() != -1) {
                homecb.setSelectedIndex(-1);
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        label = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        homecb = new javax.swing.JComboBox<>();
        awaycb = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        momentcb = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        momentTable = new javax.swing.JTable();
        min = new javax.swing.JTextField();

        jPanel6.setBackground(new java.awt.Color(30, 30, 30));
        jPanel6.setPreferredSize(new java.awt.Dimension(1103, 1498));

        label.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        label.setForeground(new java.awt.Color(255, 153, 51));
        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label.setText("MatchManagement");

        back.setText("Back");
        back.addActionListener(this::backActionPerformed);

        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("IdHome Player:");

        submit.setBackground(new java.awt.Color(204, 85, 0));
        submit.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        submit.setForeground(new java.awt.Color(255, 255, 255));
        submit.setText("Submit");
        submit.addActionListener(this::submitActionPerformed);

        jLabel16.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("IdAway Player:");

        homecb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        awaycb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel17.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Minutes:");

        momentcb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "goal", "OG", "pen", "yellow", "red", "in", "out", "injured" }));

        jLabel18.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Action:");

        save.setBackground(new java.awt.Color(204, 85, 0));
        save.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        save.setForeground(new java.awt.Color(255, 255, 255));
        save.setText("Save");
        save.addActionListener(this::saveActionPerformed);

        momentTable.setBackground(new java.awt.Color(153, 153, 153));
        momentTable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        momentTable.setForeground(new java.awt.Color(255, 153, 51));
        momentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Team", "Action", "Minute"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        momentTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(momentTable);

        min.addActionListener(this::minActionPerformed);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(back)
                        .addGap(18, 18, 18)
                        .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(submit, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(save, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(homecb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(106, 106, 106)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(momentcb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(55, 55, 55)))
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(awaycb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, Short.MAX_VALUE)))))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(homecb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(awaycb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(momentcb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(save)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submit)))
                .addContainerGap(602, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 1128, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 1214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        try {
            frame.setMatchManagement();// TODO add your handling code here:
        } catch (SQLException ex) {
            System.getLogger(MatchMoment.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_backActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed

        int tempHomeScore = 0;
        int tempAwayScore = 0;

        for (MatchEventTemp evtTmp : tempEvents) {
            String act = evtTmp.action();
            boolean isHome = evtTmp.isHomeTeam();

            if (act.equals("goal") || act.equals("pen")) {
                if (isHome) tempHomeScore++; else tempAwayScore++;
            } 
            else if (act.equals("OG")) {
                if (isHome) tempAwayScore++; else tempHomeScore++;
            }
        }

        MatchAccess matchAccess = new MatchAccess(conn);
        String formula = matchAccess.getTournamentFormula(currentMatchId);

        if ("cup".equalsIgnoreCase(formula)) {
            if (tempHomeScore == tempAwayScore) {
                JOptionPane.showMessageDialog(this, 
                    "No draw result on cup tournament", 
                    "Rule", 
                    JOptionPane.WARNING_MESSAGE);
                return; 
            }
        }
        int confirm = JOptionPane.showConfirmDialog(this, 
                "End this match?",
                "Finalize",
                JOptionPane.YES_NO_OPTION);
        
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }
        
        if (tempEvents.isEmpty()) {
            int zeroConfirm = JOptionPane.showConfirmDialog(this, 
                    "No event for a draw 0-0?",
                    "This match will 0-0",
                    JOptionPane.YES_NO_OPTION);
            if (zeroConfirm != JOptionPane.YES_NO_OPTION) return;
        }
        
        
        try {
            int eventCount = 0;
            for (MatchEventTemp evtTmp : tempEvents) {
                int detailId = matchAccess.initMoment(
                    currentMatchId, 
                    evtTmp.playerId(), 
                    evtTmp.action(), 
                    evtTmp.minute()
                );
                
                if (detailId != -1) {
                    eventCount++;
                } else {
                    System.err.println(evtTmp);
                }
            }

            String dbMessage = matchAccess.finalizeMatch(currentMatchId);
            if (dbMessage != null && dbMessage.toLowerCase().contains("success")) {
                
                JOptionPane.showMessageDialog(this, "Successfully finalize!\n" + dbMessage);
                frame.setMatchManagement();
            } else {
                JOptionPane.showMessageDialog(this, 
                        "Error with db:\n" + dbMessage, 
                        "Error Finalize", 
                        JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error Java: " + e.getMessage());
        }
            
    }//GEN-LAST:event_submitActionPerformed

    private void minActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        Player selectedPlayer = null;
        boolean isHomeTeam = true; 

        if (homecb.getSelectedIndex() != -1) {
            selectedPlayer = (Player) homecb.getSelectedItem();
            isHomeTeam = true;
            
        } else if (awaycb.getSelectedIndex() != -1) {
            selectedPlayer = (Player) awaycb.getSelectedItem();
            isHomeTeam = false;
            
        } else {
            JOptionPane.showMessageDialog(this, "Choose a player (Home or Away)!", "Miss player", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String action = momentcb.getSelectedItem().toString();
        String minuteStr = min.getText();
        try {
            int minute = Integer.parseInt(minuteStr);
            if (minute < 0 || minute > 90) {
                JOptionPane.showMessageDialog(this, "Minutes out of range(0-90)!");
                return;
            }
            MatchEventTemp tempEvt = new MatchEventTemp(
                selectedPlayer.id(), 
                selectedPlayer.name(), 
                isHomeTeam, 
                action, 
                minute
            );
            
            tempEvents.add(tempEvt);

            DefaultTableModel model = (DefaultTableModel) momentTable.getModel();
            
            model.addRow(new Object[]{
                selectedPlayer.name(),       
                isHomeTeam ? "Home" : "Away",
                action,                      
                minute                       
            });

            homecb.setSelectedIndex(-1);
            awaycb.setSelectedIndex(-1);
            min.setText("");
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Minute must be integer!", "Input syntax", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_saveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> awaycb;
    private javax.swing.JButton back;
    private javax.swing.JComboBox<String> homecb;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label;
    private javax.swing.JTextField min;
    private javax.swing.JTable momentTable;
    private javax.swing.JComboBox<String> momentcb;
    private javax.swing.JButton save;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
