/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.UI.match;

import com.mycompany.UI.frame.HomeFrame;
import static com.mycompany.UI.frame.Main.conn;
import com.mycompany.UI.team.TeamCareMain;
import static com.mycompany.UI.team.TeamManagement.TeamIDmanager;
import com.mycompany.access.MatchAccess;
import com.mycompany.access.RankingAccess;
import static com.mycompany.access.RankingAccess.listRankingTableByPoint;
import com.mycompany.access.TournamentAccess;
import com.mycompany.model.Match;
import com.mycompany.model.Ranking;
import com.mycompany.model.Tournament;
import com.mycompany.model.Versus;
import com.mycompany.service.UserSession;
import static com.mycompany.service.UserSession.isAdmin;
import java.awt.event.ItemEvent;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Minh Dep Trai
 */
public class MatchManagement extends javax.swing.JPanel {

    /**
     * Creates new form MatchManagement
     */
    private HomeFrame frame;
    private Tournament selectedTour;
    public MatchManagement(HomeFrame frame) throws SQLException {
        this.frame = frame;
        initComponents();
        TournamentAccess tacc = new TournamentAccess(conn);
        List<Tournament> tours = tacc.getAllTournaments();
        cbTour.removeAllItems();
        Finalize.setVisible(false);
        nextroundcup.setVisible(false);
        for (Tournament t : tours) {
            cbTour.addItem(t);
        }
        
        cbTour.addItemListener(e -> {
            if (e.getStateChange() == ItemEvent.SELECTED) {
                selectedTour = (Tournament) cbTour.getSelectedItem();
                
                if (selectedTour != null) {
                    try { 
                        addTableData(selectedTour.id());
                        nextroundcup.setVisible(selectedTour.formula().equals("cup"));
                    } catch (SQLException ex) {
                        System.getLogger(TeamCareMain.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                    }
                }
            }
        });
        if (cbTour.getItemCount() > 0) {
            cbTour.setSelectedIndex(0);
            Tournament first = (Tournament) cbTour.getItemAt(0);
            addTableData(first.id());
        }
    }
    
    private void addTableData(int tourId) throws SQLException {
        TournamentAccess tacc = new TournamentAccess(conn);
        List<Versus> data = tacc.getMatchesByTournamentId(tourId);
        DefaultTableModel model = (DefaultTableModel) matchTable.getModel();
        model.setRowCount(0);

        for(Versus v: data){
            boolean check = v.isDone();
            model.addRow(new Object[]{
                v.matchId(),
                v.tourName(),
                v.homeName(),
                check ? v.homeScore() : "-",
                check ? v.awayScore() : "-",
                v.awayName(),
                v.dt(),
                check ? "Done" : "Not Done"
                }
            );
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        pictureBox1 = new components.PictureBox();
        cbTour = new javax.swing.JComboBox<>();
        back = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        matchTable = new javax.swing.JTable();
        Finalize = new javax.swing.JButton();
        Finalize1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nextroundcup = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(30, 30, 30));
        jPanel2.setPreferredSize(new java.awt.Dimension(1103, 1498));

        jPanel3.setBackground(new java.awt.Color(30, 30, 30));

        pictureBox1.setImage(new javax.swing.ImageIcon("D:\\NewProject\\src\\main\\java\\com\\mycompany\\newproject\\icons8-search-50 (1).png"));

        cbTour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        back.setText("Back");
        back.addActionListener(this::backActionPerformed);

        matchTable.setBackground(new java.awt.Color(153, 153, 153));
        matchTable.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        matchTable.setForeground(new java.awt.Color(255, 153, 51));
        matchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Tournament", "Home", "Home Score", "Away Score", "Away", "Date", "State"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        matchTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                matchTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(matchTable);

        Finalize.setBackground(new java.awt.Color(255, 102, 0));
        Finalize.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        Finalize.setForeground(new java.awt.Color(255, 255, 255));
        Finalize.setText("Finalize");
        Finalize.addActionListener(this::FinalizeActionPerformed);

        Finalize1.setBackground(new java.awt.Color(255, 102, 0));
        Finalize1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        Finalize1.setForeground(new java.awt.Color(255, 255, 255));
        Finalize1.setText("Reload");
        Finalize1.addActionListener(this::Finalize1ActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(187, 187, 187));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Match Management");

        nextroundcup.setBackground(new java.awt.Color(255, 102, 0));
        nextroundcup.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        nextroundcup.setForeground(new java.awt.Color(255, 255, 255));
        nextroundcup.setText("Generate Next Round");
        nextroundcup.addActionListener(this::nextroundcupActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(418, 418, 418)
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nextroundcup)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(back)
                                    .addGap(290, 290, 290)
                                    .addComponent(pictureBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Finalize)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Finalize1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbTour, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 961, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(back)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(pictureBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Finalize1)
                                    .addComponent(Finalize)
                                    .addComponent(cbTour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nextroundcup)
                .addContainerGap())
        );

        jPanel2.add(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1176, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 280, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        frame.setHomePanel();        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void matchTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_matchTableMouseClicked
        int id = Integer.parseInt(matchTable.getValueAt(matchTable.getSelectedRow(), 0).toString());
        MatchAccess macc = new MatchAccess(conn);
        Match match;
        try {
            match = macc.findMatchById(id);
            Finalize.setVisible(!match.isDone() && isAdmin());
        } catch (SQLException ex) {
            System.getLogger(MatchManagement.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
    }//GEN-LAST:event_matchTableMouseClicked

    private void FinalizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalizeActionPerformed
        int id = Integer.parseInt(matchTable.getValueAt(matchTable.getSelectedRow(), 0).toString());
        MatchAccess macc = new MatchAccess(conn);
        try {
            Match match = macc.findMatchById(id);
            if(match.isDone()) return;
            
            frame.setMomentAdd(id, match.homeId(), match.awayId());
        } catch (SQLException ex) {
            System.getLogger(MatchManagement.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_FinalizeActionPerformed

    private void Finalize1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Finalize1ActionPerformed
        Tournament currentTour = (Tournament) cbTour.getSelectedItem();
        if (currentTour == null) {
            return;
        }

        this.selectedTour = currentTour;
        try {
            
            nextroundcup.setVisible(currentTour.formula().equals("cup") && isAdmin());
            
            TournamentAccess tacc = new TournamentAccess(conn);
            List<Tournament> tours = tacc.getAllTournaments();
            cbTour.removeAllItems();
            Finalize.setVisible(false);
            nextroundcup.setVisible(false);
            for (Tournament t : tours) {
                cbTour.addItem(t);
            }
            if (cbTour.getItemCount() > 0) {
                cbTour.setSelectedItem(currentTour);
                Tournament first = (Tournament) cbTour.getItemAt(0);
                addTableData(currentTour.id());
            }
            
        } catch (SQLException ex) {
            System.getLogger(MatchManagement.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_Finalize1ActionPerformed

    private void nextroundcupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextroundcupActionPerformed
        int tourId = selectedTour.id();
        TournamentAccess tacc = new TournamentAccess(conn);
        String result = tacc.generateNextCupRound(tourId);
        if (result.contains("Created")) {
            JOptionPane.showMessageDialog(this, result);
            try { 
                addTableData(tourId);
            } catch (SQLException ex) {
                System.getLogger(MatchManagement.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        } else if (result.contains("Champion")) {
            JOptionPane.showMessageDialog(this, result, "Congratulation!", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, result, "Cannot generate next round", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_nextroundcupActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Finalize;
    private javax.swing.JButton Finalize1;
    private javax.swing.JButton back;
    private javax.swing.JComboBox<Object> cbTour;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable matchTable;
    private javax.swing.JButton nextroundcup;
    private components.PictureBox pictureBox1;
    // End of variables declaration//GEN-END:variables

    
}
